# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 12:48
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import django.db.models.manager
import widgy.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('widgy_mezzanine', '0002_create_widgycalloutwidget'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='widgypage',
            managers=[
                ('_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='widgypage',
            name='root_node',
            field=widgy.db.fields.VersionedWidgyField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='review_queue.ReviewedVersionTracker', verbose_name='widgy content'),
        ),
    ]
